version: '3'

services:
  node:
    build: ./docker/node
    volumes:
      - ./:/oidc-provider-dynamodb-adapter
    links:
      - localstack
  localstack:
    image: localstack/localstack
    ports:
      - '4569:4569'
